apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: smitdarji/k8s:v0.0.10
        ports:
        - containerPort: 80
