apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: webapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: smitdarji/k8s:v0.0.10   # auto-updated by script
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: webapps
spec:
  selector:
    app: login
  ports:
  - port: 80
    targetPort: 80
  type: NodePort
