apiVersion: v1
kind: Service
metadata:
  name: k8s-app-service
  namespace: webapps
spec:
  type: NodePort
  selector:
    app: k8s-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
